## Preprocessing

In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\lenovo\\Desktop\\Digital Lync-Data Science'

In [3]:
import pandas as pd

In [4]:
train = pd.read_csv(r"F:\Desktop\train.csv")
test = pd.read_csv(r"F:\Desktop\test.csv")

In [5]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [7]:
train.shape

(891, 12)

In [8]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
train = train.drop(['Cabin'], axis = 'columns')

In [10]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [11]:
test.shape

(418, 11)

In [12]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [13]:
test = test.drop(['Cabin'], axis = 'columns')

In [14]:
test.isnull().sum()

PassengerId     0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
Embarked        0
dtype: int64

In [15]:
train = train.set_index('PassengerId')

In [16]:
train.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Embarked  
PassengerId                                                    
1                1      0         A/5 21171   7.2500        S  
2                1      0          PC 17599  71.2833        C  
3                0      0  STON/O2. 3101282   7.9250        S  
4                1      0            113803  53.1000        S  
5                0      0            373450   8.0500        S

In [17]:
test = test.set_index('PassengerId')

In [18]:
test.head()

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

              Age  SibSp  Parch   Ticket     Fare Embarked  
PassengerId                                                 
892          34.5      0      0   330911   7.8292        Q  
893          47.0      1      0   363272   7.0000        S  
894          62.0      0      0   240276   9.6875        Q  
895          27.0      0      0   315154   8.6625        S  
896          22.0      1      1  3101298  12.2875        S

In [19]:
print(train.isnull().sum(), test.isnull().sum())

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      2
dtype: int64 Pclass       0
Name         0
Sex          0
Age         86
SibSp        0
Parch        0
Ticket       0
Fare         1
Embarked     0
dtype: int64


## Imputation

In [20]:
mode = train['Embarked'].value_counts().index[0]
train['Embarked'] = train['Embarked'].fillna(mode)

# Imputation

from sklearn.preprocessing import Imputer
median_imp = Imputer(missing_values = 'NaN', strategy = 'median', axis = 0, copy = False)

median_imp.fit_transform(train['Age'].values.reshape(-1, 1))
median_imp.fit_transform(test['Age'].values.reshape(-1, 1))
median_imp.fit_transform(test['Fare'].values.reshape(-1, 1))
print(train.isnull().sum(), test.isnull().sum())

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64 Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64


In [21]:
print(train.dtypes, test.dtypes)

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object


In [22]:
# Now we can delete the columns which are not required and categorical.Our target variable is Survived

train1 = train.drop(['Name', 'Ticket'], axis = 1, inplace = False)
test1 = test.drop(['Name', 'Ticket'], axis = 1, inplace = False)

In [23]:
print(train1.info(), test1.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 8 columns):
Survived    891 non-null int64
Pclass      891 non-null int64
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    891 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.6+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 7 columns):
Pclass      418 non-null int64
Sex         418 non-null object
Age         418 non-null float64
SibSp       418 non-null int64
Parch       418 non-null int64
Fare        418 non-null float64
Embarked    418 non-null object
dtypes: float64(2), int64(3), object(2)
memory usage: 26.1+ KB
None None


## Converting into 'category' type

In [27]:
categorical_cols = ['Survived', 'Pclass', 'Sex', 'Embarked']

for col in categorical_cols:
    train1[col] = train1[col].astype('category')
    if col == 'Survived':
        continue
    test1[col] = test1[col].astype('category')

In [28]:
print(train1.dtypes, test.dtypes)

Survived    category
Pclass      category
Sex         category
Age          float64
SibSp          int64
Parch          int64
Fare         float64
Embarked    category
dtype: object Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object


In [29]:
dummy_cols = categorical_cols[1:]

## Creating dummies for categorical variable except target variable

In [30]:
train1 = pd.get_dummies(train1, columns = dummy_cols, prefix_sep = '_', drop_first = True)
test1 = pd.get_dummies(test1, columns = dummy_cols, prefix_sep = '_', drop_first = True)

In [31]:
train1.shape

(891, 10)

In [32]:
train1.head()

Survived   Age  SibSp  Parch     Fare  Pclass_2  Pclass_3  \
PassengerId                                                             
1                  0  22.0      1      0   7.2500         0         1   
2                  1  38.0      1      0  71.2833         0         0   
3                  1  26.0      0      0   7.9250         0         1   
4                  1  35.0      1      0  53.1000         0         0   
5                  0  35.0      0      0   8.0500         0         1   

             Sex_male  Embarked_Q  Embarked_S  
PassengerId                                    
1                   1           0           1  
2                   0           0           0  
3                   0           0           1  
4                   0           0           1  
5                   1           0           1

In [33]:
test1.head()

Age  SibSp  Parch     Fare  Pclass_2  Pclass_3  Sex_male  \
PassengerId                                                              
892          34.5      0      0   7.8292         0         1         1   
893          47.0      1      0   7.0000         0         1         0   
894          62.0      0      0   9.6875         1         0         1   
895          27.0      0      0   8.6625         0         1         1   
896          22.0      1      1  12.2875         0         1         0   

             Embarked_Q  Embarked_S  
PassengerId                          
892                   1           0  
893                   0           1  
894                   1           0  
895                   0           1  
896                   0           1

In [34]:
x = train1.drop(['Survived'], axis = 1)
y = train1['Survived']

In [35]:
x.head()

Age  SibSp  Parch     Fare  Pclass_2  Pclass_3  Sex_male  \
PassengerId                                                              
1            22.0      1      0   7.2500         0         1         1   
2            38.0      1      0  71.2833         0         0         0   
3            26.0      0      0   7.9250         0         1         0   
4            35.0      1      0  53.1000         0         0         0   
5            35.0      0      0   8.0500         0         1         1   

             Embarked_Q  Embarked_S  
PassengerId                          
1                     0           1  
2                     0           0  
3                     0           1  
4                     0           1  
5                     0           1

In [36]:
y.head()

PassengerId
1    0
2    1
3    1
4    1
5    0
Name: Survived, dtype: category
Categories (2, int64): [0, 1]

## Decision Tree

In [37]:
from sklearn import tree

In [61]:
model = tree.DecisionTreeClassifier(criterion = 'entropy',min_impurity_decrease=0.1)
model.fit(x, y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.1, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [62]:
train_preds = model.predict(x)     # x is everything in data except survived
test_preds = model.predict(test1)

## confusion matrix and classification report

In [63]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

conf_mat = confusion_matrix(y, train_preds)       # confusion matrix for y--> ['Survived'] and train_preds-->predict(x)
class_rep = classification_report(y, train_preds) # classification report for y--> ['Survived'] and train_preds-->predict(x)
print(conf_mat)
print(class_rep)

[[468  81]
 [109 233]]
             precision    recall  f1-score   support

          0       0.81      0.85      0.83       549
          1       0.74      0.68      0.71       342

avg / total       0.78      0.79      0.78       891



In [64]:
submission = pd.DataFrame(test_preds, index = test1.index, columns = ['Survived'])
submission.to_csv('DTsubmission.csv', index = True)

In [65]:
submission.head()

Survived
PassengerId          
892                 0
893                 1
894                 0
895                 0
896                 1

In [54]:
model1 = tree.DecisionTreeClassifier(criterion='gini')

In [46]:
model1.fit(x, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [47]:
train_pred = model1.predict(x)
test_pred = model1.predict(test1)

In [48]:
train_pred[:5]

array([0, 1, 1, 1, 0], dtype=int64)

In [49]:
test_pred[:5]

array([0, 0, 1, 1, 1], dtype=int64)

In [50]:
conf_mat = confusion_matrix(y, train_preds)
print(conf_mat)

[[547   2]
 [ 16 326]]


In [51]:
calss_rep = classification_report(y, train_preds)
print(calss_rep)

             precision    recall  f1-score   support

          0       0.97      1.00      0.98       549
          1       0.99      0.95      0.97       342

avg / total       0.98      0.98      0.98       891



In [53]:
sub = pd.DataFrame(test1, index = test1.index, columns = ['Survived'])
sub.head()

Survived
PassengerId          
892               NaN
893               NaN
894               NaN
895               NaN
896               NaN